# Generated by Django 5.0 on 2023-12-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='author_images/default.jpg', upload_to='autor_image/'),
            preserve_default=False,
        ),
    ]
